version: "3.8"
services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    env_file:
      - ./.env
    command: ["yarn", "start"]
  db:
    image: postgres:14.4
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: faucet_discord
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
