version: "3.8"
services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    env_file:
      - ./.env
    command: ["yarn", "dev"]
  db-dev:
    image: postgres:14.4
    profiles: [scripts]
    environment:
      POSTGRES_DB: faucet_discord
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
